#! /bin/bash
# This script is created for updating ac01 upto ac08 source (on 2007-03-27)
# Probably, we need to write a script to compare the files in /backup 
# directoty with the ones in the as server and update the local /backup
# directory accordingly.

if [ ! -d $HOME/book ]
  then mkdir $HOME/book;
else rm -rf $HOME/book/*
fi

cd $HOME/book; tar -zxvf /backup/book/*; cd $HOME

# The compilation problem of fontutils-0.7 (in GCC 4.4) need to be adjusted.
cd /src1/CHDB; rm -rf *;  tar -zxvf /backup/CHDB/*; 
cd CCCII; tar -zxvf /backup/CCCII/*; 
cd ../ChFont; tar -zxvf /backup/ChFont/*; 
cd $HOME

if [ ! -d $HOME/setup ]
  then mkdir $HOME/setup;
else rm -rf $HOME/setup/*
fi

cd $HOME/setup; tar -zxvf /backup/setup/*; cd usr-local-bin;
sudo cp * /usr/local/bin; cd ../inet; cp webLink.html $HOME/inet;
if [ ! -d $HOME/inet/ShellScripts ]
  then mkdir $HOME/inet/ShellScripts;
else rm -rf $HOME/inet/ShellScripts/*
fi
cp ShellScripts/* $HOME/inet/ShellScripts; cd ../ScmEnv;
if [ ! -d $HOME/ScmEnv ]
  then mkdir $HOME/ScmEnv;
else rm -rf $HOME/ScmEnv/*
fi
cp * $HOME/ScmEnv;


if [ ! -d /src2/DSSSL ]
  then sudo mkdir /src2/DSSSL;
       sudo chown hsu:hsu /src2/DSSSL
else rm -rf /src2/DSSSL/*
fi

cd /src2/DSSSL; tar -zxvf /backup/DSSSL/*

if [ ! -d /src1/LinuxRef ]
  then sudo mkdir /src1/LinuxRef;
       sudo chown hsu:hsu /src1/LinuxRef
else rm -rf /src1/LinuxRef/*
fi

cd /src1/LinuxRef; tar -zxvf /backup/LinuxRef/*

if [ ! -d /src2/OpenJade ]
  then sudo mkdir /src2/OpenJade;
       sudo chown hsu:hsu /src2/OpenJade
else rm -rf /src2/OpenJade/*
fi

cd /src2/OpenJade; tar -zxvf /backup/OpenJade/*

if [ ! -d /src2/guile-2 ]
  then sudo mkdir /src2/guile-2;
       sudo chown hsu:hsu /src2/guile-2
else rm -rf /src2/guile-2/*
fi

cd /src2/guile-2; tar -zxvf /backup/guile-2/*

# The DTDs and CATALOG files used by OpenJade are collected here.
cd /usr/local/share/sgml; sudo tar -zxvf /backup/sgml/*


# ld.so.conf is needed while running ldconfig to update share object database,
# i.e. /etc/ld.so.cache 
# In the past, Ubuntu never include /usr/local/lib in its configuration path.
# Finally, it got fixed in /etc/ld.so.conf.d/libc.conf.
# sudo cp /tmp/ld.so.conf /etc
