#! /bin/bash
subDir='book CCCII CHDB ChFont CHinese DocInSgml DSSSL emacs-21 guile-2 KVM-tool LinuxRef NetLab OpenJade psgml setup sgml TeXSrc UML-tool'

# The official source backup  files are stored in Amath-Server!
if [ x`hostname` != "xAmath-Server" ]
  then  for sD in $subDir
          do
            cd /backup/${sD}
            rm -rf *
            scp -r as:`pwd`/* .
          done
fi

cd /home/CHinese
tar -zxvf /backup/CHinese/*tgz 
cd /src1/CHDB
tar -zxvf /backup/CHDB/*tgz 
cd CCCII
tar -zxvf /backup/CCCII/*tgz 
cd /src1/emacs-21
tar -zxvf /backup/emacs-21/emacs-21-*.tgz
cd /src1/LinuxRef
tar -zxvf /backup/LinuxRef/*.tgz
cd  /src2/DSSSL
tar -zxvf /backup/DSSSL/*.tgz 
cd  /src2/guile-2 
tar -zxvf /backup/guile-2/guile-*.tgz 
cd  /src2/OpenJade
tar -zxvf /backup/OpenJade/OpenJade-*.tgz
cd /src3/NetLab 
tar -zxvf /backup/NetLab/NetLab-*.tgz 
cd Nets 
./MakeDevNodes.sh ../UmlRfs
echo "Created device files in ../UmlRfs are:" 
ls -l  ../UmlRfs/dev 
cd $HOME; mkdir psgml; cd psgml
tar -zxvf /backup/psgml/psgml*tgz
echo "Under `pwd`, type make; sudo make install; rm *.elc"
echo "  to finish your installation after Chinese emacs is up and running."
cd $HOME; mkdir setup; cd setup
tar -zxvf /backup/setup/*tgz
sudo cp usr-local-bin/* /usr/local/bin
sudo ln -s /usr/local/bin/rmnt /usr/local/bin/rumnt 
cp profiles/profile $HOME/.profile
cp profiles/emacs $HOME/.emacs
mkdir $HOME/inet $HOME/inet/ShellScripts $HOME/ScmEnv
cp inet/webLink.html $HOME/inet
cp inet/ShellScripts/* $HOME/inet/ShellScripts
cp ScmEnv/my.scm $HOME/ScmEnv
cd /usr/local/share/sgml
sudo tar -zxvf /backup/sgml/sgml*tgz
