#! /bin/sh
subDir='book CCCII CHDB ChFont CHinese DocInSgml DSSSL emacs-21 guile-2 KVM-tool LinuxRef NetLab OpenJade psgml setup sgml TeXSrc UML-tool'

for sD in $subDir
  do
    mkdir /backup/${sD}
    chown hsu:hsu /backup/${sD}
  done

ls -l  /backup

mkdir /home/CHinese /src1/CHDB /src1/emacs-21 /src1/LinuxRef /src2/DSSSL /src2/guile-2 /src2/OpenJade /src3/NetLab 
chown hsu:hsu /home/CHinese /src1/CHDB /src1/emacs-21 /src1/LinuxRef /src2/DSSSL /src2/guile-2 /src2/OpenJade /src3/NetLab 
