#! /bin/bash 

if [ ! `which resize2fs` ]
  then echo "Need to install e2fsprogs package, first. Quit."
       exit 1
fi

if [ $# != 2 ]
  then echo " $ $0 FileNameToBeResized AmountOfExtraSpaceInMegaByte"
       exit 2
fi

if [ ! -f $1 ] 
  then echo "$1 does not exist, quit."
       exit 3
fi 

if [ ! $2 -gt 0 ] 
  then echo "$2 must be positive integer, quit."
       exit 4
fi 

FileSize=`ls -l $1 | cut -d" " -f 5`
OneM=$((1024*1024))
Offset=$(($(($FileSize/$OneM)) + 1))
echo $Offset

echo "Point of no return, Do you really want to resize $1?, answer: yes/no"
read Answer

if [ $Answer = "yes" ] 
  then dd if=/dev/zero of=$1 bs=1M seek=$Offset count=$2

  # After resizing, run e2fsck to update the filesystem information.
       e2fsck -f $1
       resize2fs $1
  if [ $? = 0 ]
    then echo "$1 resized successfully."
  fi
else echo "Quit!"
     exit 5
fi
